services:
  db:
    image: postgres:16-alpine # Используем легкий и актуальный образ PostgreSQL
    container_name: notification_db

    # Порт для доступа к базе данных
    # 5432 — стандартный порт PostgreSQL
    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: notification         # Имя базы данных, которая будет создана
      POSTGRES_USER: postgres           # Имя суперпользователя
      POSTGRES_PASSWORD: 9376570167   # Пароль для суперпользователя

    # Сохранение данных в томе (для постоянства)
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # Политика перезапуска
    restart: always

# Объявление внешнего тома для сохранения данных
volumes:
  postgres_data: